name: website
description: The Website For The OpenVM Project.
version: 1.0.0
repository: https://github.com/The-OpenVM-Project/Website

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  web: ^0.5.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^4.0.0
  peanut: ^5.1.0
